### ISSUE TITLE
JBR fails to start in case of corrupted annotations.yaml file

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/jbr#100]
```
2020-04-08 20:16:14,997 INFO [main] o.j.b.j.JBRBrowserCLA [JBRBrowserCLA.kt:140] Markup folder: /Users/oleg/.jbr_browser/genomes
2020-04-08 20:16:15,000 INFO [main] o.j.b.j.JBRBrowserCLA [JBRBrowserCLA.kt:141] Caches directory: /Users/oleg/.jbr_browser/cache
2020-04-08 20:16:15,001 INFO [main] o.j.b.j.JBRBrowserCLA [JBRBrowserCLA.kt:143] Updating annotations '/Users/oleg/.jbr_browser/genomes'...
2020-04-08 20:16:15,008 INFO [main] o.j.b.j.JBRBrowserCLA [JBRBrowserCLA.kt:146] Loading plugins...
2020-04-08 20:16:15,379 INFO [main] o.j.b.b.JBRPlugin [JBRPlugin.kt:114] Loaded plugin: JBR base tracks
2020-04-08 20:16:15,383 INFO [main] o.j.b.b.JBRPlugin [JBRPlugin.kt:114] Loaded plugin: Search ENCODE support
2020-04-08 20:16:15,386 INFO [main] o.j.b.b.JBRPlugin [JBRPlugin.kt:114] Loaded plugin: SPAN support
2020-04-08 20:16:15,389 INFO [main] o.j.b.b.JBRPlugin [JBRPlugin.kt:114] Loaded plugin: BED files tuning
2020-04-08 20:16:15,392 INFO [main] o.j.b.b.JBRPlugin [JBRPlugin.kt:114] Loaded plugin: Overlap BED tracks
2020-04-08 20:16:15,393 INFO [main] o.j.b.b.JBRPlugin [JBRPlugin.kt:106] Successfully loaded plugins: 5
2020-04-08 20:16:15,393 INFO [main] o.j.b.j.JBRBrowserCLA [JBRBrowserCLA.kt:155] Launching browser...
2020-04-08 20:16:15,414 INFO [main] o.j.b.j.JBRDesktopApp [JBRDesktopApp.kt:34] Loading supported genomes config: /Users/oleg/.jbr_browser/genomes/annotations.yaml ...
2020-04-08 20:16:15,430 ERROR [main] o.j.b.j.JBRBrowserCLA [JBRBrowserCLA.kt:182] Cannot launch browser: Cannot parse: [{species=Schistosoma mansoni, description=https://schistodb.net/common/downloads/release-46/, sequence=https://schistodb.net/common/downloads/release-46/Smansoni/fasta/SchistoDB-46_Smansoni_ESTs.fasta}]
java.lang.RuntimeException: Cannot parse: [{species=Schistosoma mansoni, description=https://schistodb.net/common/downloads/release-46/, sequence=https://schistodb.net/common/downloads/release-46/Smansoni/fasta/SchistoDB-46_Smansoni_ESTs.fasta}]
	at org.jetbrains.bio.genome.AnnotationsConfigLoader$YamlMapper.get(AnnotationsConfig.kt:225)
	at org.jetbrains.bio.genome.AnnotationsConfigLoader.parseYaml$bioinf_commons(AnnotationsConfig.kt:125)
	at org.jetbrains.bio.genome.AnnotationsConfigLoader.loadOrCreateBuild2ConfigMapping(AnnotationsConfig.kt:134)
	at org.jetbrains.bio.genome.AnnotationsConfigLoader.init(AnnotationsConfig.kt:69)
	at org.jetbrains.bio.jbr.JBRDesktopApp.start(JBRDesktopApp.kt:35)
	at org.jetbrains.bio.jbr.JBRBrowserCLA$main$2$1.invoke(JBRBrowserCLA.kt:179)
	at org.jetbrains.bio.jbr.JBRBrowserCLA$main$2$1.invoke(JBRBrowserCLA.kt:23)
	at org.jetbrains.bio.util.OptionParserExtensionsKt.parse(OptionParserExtensions.kt:71)
	at org.jetbrains.bio.util.OptionParserExtensionsKt.parse$default(OptionParserExtensions.kt:27)
	at org.jetbrains.bio.jbr.JBRBrowserCLA.main(JBRBrowserCLA.kt:88)
Caused by: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
	at org.jetbrains.bio.genome.AnnotationsConfigLoader$YamlMapper.get(AnnotationsConfig.kt:212)
	... 9 common frames omitted
```

**Comment by olegs** [comment]
Example of incorrect annotations:
```
---
version: 4
genomes:
  # http://www.ensembl.org/Mus_musculus
  mm9:
    species: Mus musculus
    ucsc_alias: mm9
    aliases: NCBIM37
    description: 'Jul. 2007, genes Ensembl 67 (May 2012)'
    biomart:
      url: http://may2012.archive.ensembl.org/biomart/martservice
      dataset: mmusculus_gene_ensembl
    gtf: ftp://anonymous@ftp.ensembl.org/pub/release-67/gtf/mus_musculus/Mus_musculus.NCBIM37.67.gtf.gz
    chr_alt_name_to_canonical:
      - MT: chrM

    ucsc_annotations_legacy: True
    repeats: http://hgdownload.cse.ucsc.edu/goldenPath/mm9/database/rmsk.txt.gz
    cytobands: http://hgdownload.cse.ucsc.edu/goldenPath/mm9/database/cytoBand.txt.gz
    gaps: http://hgdownload.cse.ucsc.edu/goldenPath/mm9/database/gap.txt.gz
    # centromeres:  n/a
    cgis: http://hgdownload.cse.ucsc.edu/goldenPath/mm9/database/cpgIslandExt.txt.gz
    sequence: http://hgdownload.cse.ucsc.edu/goldenPath/mm9/bigZips/mm9.2bit
    chromsizes: http://hgdownload.cse.ucsc.edu/goldenPath/mm9/bigZips/mm9.chrom.sizes

  # http://metazoa.ensembl.org/Schistosoma_mansoni/Info/Index
  SmasoniESTs46:
    species: Schistosoma mansoni
    description: https://schistodb.net/common/downloads/release-46/
    sequence: https://schistodb.net/common/downloads/release-46/Smansoni/fasta/SchistoDB-46_Smansoni_ESTs.fasta
```
