### ISSUE TITLE
IllegalArgumentException: offset 249250621 out of range: 249250621 not in [0, 171115067)

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/jbr#132]
Please just log a warning, do not throw an exception in case:
* Open browser, see default `chr1:0-249250621`
* Change `chr1` to `chr6` and press `Enter`
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: offset 249250621 out of range: 249250621 not in [0, 171115067)
	at org.jetbrains.bio.browser.util.TrackUIUtil.genomeToScreen(TrackUIUtil.kt:481)
	at org.jetbrains.bio.browser.desktop.Header$Companion.drawPointer(BrowserHeaders.kt:43)
	at org.jetbrains.bio.browser.desktop.ChromosomeHeader.paint(BrowserHeaders.kt:120)
	at javax.swing.JComponent.paintChildren(JComponent.java:903)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JViewport.paint(JViewport.java:728)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by iromeo** [comment]
This fix makes rendering inconsistent, e.g. see screenshot. `chrY` is much shorter that `chr1`. While genes track shown correctly, the header with CytoBands shown not correct, it should and  in the end of ChrY, not Chr1. 

![image](https://github.com/JetBrains-Research/jbr/assets/72933/c3500f12-8dfa-4d4a-b8b2-fbf09a6aa519)
Looks like gene `CTBP2P1` ends at `q11.21` but should be `q12`:
![image](https://github.com/JetBrains-Research/jbr/assets/72933/c1704064-82b9-4283-8bfe-630a3b42dd98)


Instead I suggest changing the user request parsing (i.e. in `fun parseSingleLocation(text: String, genomeQuery: GenomeQuery): LocationReference`, see BrowserInput.kt), so `chrY:0-248956422` will be replaced with `chrY:0-57227415` because `57227415`, i.e. trimmed by chromosome Y size.
