### ISSUE TITLE
Genomes editing UI usability issues - cannot register CHM13 genome

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/jbr#150]
Hi, I decided to try configure [CHM13](https://github.com/marbl/CHM13#v11) reference, but didn't manage to do it.

* I presses "+" button and start filling the fields
* When editing **new** genome, I'd like to check existing ones (e.g. hg38) as an example and copy some fields. E.g. not clear what string should be `Species`, but before switch to other genome (e.g. hg38) I have to fill all required files and save them, so I was forced to fill fields with fake strings like `foooo`
* When editing genome fields iteratively (e.g. fix field, press "Save", fix field, press "Save"). `Save` button is frequently grayed, so I have to switch to some other genome and back to current in order to make it enabled.
* Not all required files are available online, so I used paths to existing files on my local machine:
![image](https://user-images.githubusercontent.com/72933/124970952-4f192780-e031-11eb-8e4f-1ab3aaaa66cf.png)
* after restart, if I select new CHM13 genome, JBR suggests to close tracks and does nothing. No error, etc. Log file:
```
2021-07-08 21:03:46,246 INFO [main] o.j.b.b.JBRPlugin [JBRPlugin.kt:50] Plugin BED files tuning loaded 1 extension point(s) TrackViewExtensionPoint
2021-07-08 21:03:46,310 INFO [main] o.j.b.b.GenomeBrowser [GenomeBrowser.kt:312] Initializing browser: Preprocessing 1 tracks
2021-07-08 21:03:46,315 INFO [ForkJoinPool-2-worker-19] o.j.b.b.GenomeBrowser [LoggerExtensions.kt:35] Preprocessing track 'Ensembl Genes'...
2021-07-08 21:03:46,328 INFO [ForkJoinPool-2-worker-19] o.j.b.b.GenomeBrowser [LoggerExtensions.kt:35] Preprocessing track 'Ensembl Genes': done in 10.09 ms
2021-07-08 21:03:46,330 INFO [ForkJoinPool-2-worker-19] o.j.b.u.Progress [Progress.kt:46] Preprocessing: 100% (1/1), Elapsed time: 15 ms [done]
2021-07-08 21:04:00,712 INFO [AWT-EventQueue-0] o.j.b.u.PathExtensions [LoggerExtensions.kt:35] recalculating /Users/romeo/.jbr_browser/genomes/chm13-t2t-v1.1/chm13-t2t-v1.1.chrom.sizes...
2021-07-08 21:04:00,728 INFO [AWT-EventQueue-0] o.j.b.g.UCSC [UCSC.kt:46] Download [http://localhost//Users/romeo/work/_annotations_/reference/chm13t2t-v1.1.chrom.sizes] to /Users/romeo/.jbr_browser/genomes/chm13-t2t-v1.1/chm13-t2t-v1.1.chrom_tmp471221588466458245.sizes
2021-07-08 21:04:01,007 ERROR [AWT-EventQueue-0] o.j.b.u.PathExtensions [LoggerExtensions.kt:25] recalculating /Users/romeo/.jbr_browser/genomes/chm13-t2t-v1.1/chm13-t2t-v1.1.chrom.sizes: [FAILED] after 291.1 ms
java.lang.RuntimeException: Failed to download http://localhost//Users/romeo/work/_annotations_/reference/chm13t2t-v1.1.chrom.sizes to /Users/romeo/.jbr_browser/genomes/chm13-t2t-v1.1/chm13-t2t-v1.1.chrom_tmp471221588466458245.sizes
	at org.jetbrains.bio.genome.UCSCKt.downloadTo(UCSC.kt:54)
	at org.jetbrains.bio.genome.UCSCKt.downloadTo$default(UCSC.kt:42)
	at org.jetbrains.bio.genome.Genome$Companion$chromSizesFromPath$1.invoke(Genome.kt:410)
	at org.jetbrains.bio.genome.Genome$Companion$chromSizesFromPath$1.invoke(Genome.kt:223)
	at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1$1$block$1.invoke(PathExtensions.kt:331)
	at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1$1$block$1.invoke(PathExtensions.kt)
	at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1$1.invoke(PathExtensions.kt:467)
	at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1$1.invoke(PathExtensions.kt)
	at org.jetbrains.bio.util.LoggerExtensionsKt.time(LoggerExtensions.kt:18)
	at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1.invoke(PathExtensions.kt:328)
	at org.jetbrains.bio.util.PathExtensionsKt$checkOrRecalculate$1.invoke(PathExtensions.kt)
	at org.jetbrains.bio.util.LockManager.synchronized(LockManager.kt:39)
	at org.jetbrains.bio.util.PathExtensionsKt.checkOrRecalculate(PathExtensions.kt:312)
	at org.jetbrains.bio.util.PathExtensionsKt.checkOrRecalculate$default(PathExtensions.kt:309)
	at org.jetbrains.bio.genome.Genome$Companion.chromSizesFromPath(Genome.kt:404)
	at org.jetbrains.bio.genome.Genome$Companion.access$chromSizesFromPath(Genome.kt:223)
	at org.jetbrains.bio.genome.Genome$Companion$get$1$1.invoke(Genome.kt:270)
	at org.jetbrains.bio.genome.Genome$Companion$get$1$1.invoke(Genome.kt:223)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.bio.genome.Genome.getChromSizesMap$bioinf_commons(Genome.kt)
	at org.jetbrains.bio.genome.Genome$chromosomes$2.invoke(Genome.kt:140)
	at org.jetbrains.bio.genome.Genome$chromosomes$2.invoke(Genome.kt:31)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.bio.genome.Genome.getChromosomes(Genome.kt)
	at org.jetbrains.bio.genome.GenomeQuery$chromosomes$2.invoke(GenomeQuery.kt:26)
	at org.jetbrains.bio.genome.GenomeQuery$chromosomes$2.invoke(GenomeQuery.kt:10)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.bio.genome.GenomeQuery.getChromosomes(GenomeQuery.kt)
	at org.jetbrains.bio.genome.GenomeQuery.get(GenomeQuery.kt:29)
	at org.jetbrains.bio.browser.model.SingleLocationBrowserModel.<init>(SingleLocationBrowserModel.kt:16)
	at org.jetbrains.bio.browser.desktop.TrackListController.doNewSession(TrackListController.kt:342)
	at org.jetbrains.bio.browser.desktop.BrowserActionsToolbar$2.mouseClicked(BrowserActionsToolbar.kt:66)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:80 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.jetbrains.bio.genome.UCSCKt.tryGet(UCSC.kt:24)
	at org.jetbrains.bio.genome.UCSCKt.downloadHttp(UCSC.kt:100)
	at org.jetbrains.bio.genome.UCSCKt.downloadTo(UCSC.kt:51)
	... 62 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 75 common frames omitted
2021-07-08 21:04:34,834 INFO [AWT-EventQueue-0] o.j.b.u.Exec [Exec.kt:46] open -R /Users/romeo/.jbr_browser/logs/jbr.log
```
* According to the above log file some fields should be URLs, but there is no fields values validation. According to the fields' hint file paths are valid values. More over URL-only limitation here isn't convenient.

---
Summary: at the moment it isn't clear how to register new CHM13 genome via this dialog

**Comment by iromeo** [comment]
I could register the genome using hack:
1. Place files into proper folder:
```
~/.jbr_browser/genomes/chm13t2t-v1.1
├── chm13t2t-v1.1.2bit
├── chm13t2t-v1.1.chrom.sizes
├── chm13t2t-v1.1.gap.txt.gz
└── chm13t2t-v1.1.gene_annotation.v4.gff3.gz
```
2. Use config:
```
 chm13t2t-v1.1:⏎
    species: Homo sapiens⏎
    description: hg38 with telomores resolved⏎
    aliases:⏎
    gtf: /Users/romeo/work/_annotations_/reference/chm13t2t-v1.1.gene_annotation.v4.gff3.gz⏎
    sequence: /Users/romeo/work/_annotations_/reference/chm13t2t-v1.1.2bit⏎
    chromsizes: http://localhost//Users/romeo/work/_annotations_/reference/chm13t2t-v1.1.chrom.sizes⏎
    gaps: /Users/romeo/work/_annotations_/reference/chm13t2t-v1.1.gap.txt.gz⏎
```
