### ISSUE TITLE
ERROR lateinit property

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/jbr#20]
```
[Mar 21, 2019 23:04:00] BigBed empty file format: https://artyomovlab.wustl.edu/publications/supp_materials/aging/chipseq/Y20O20/peaks/H3K36me3/macs_broad/bigBed/YD_YD5_H3K36me3_broad1.0E-4_peaks.bb = (bed3, '	')
[Mar 21, 2019 23:04:00] ERROR TrackView Failed to preprocess track MACS YD_YD5_H3K36me3_broad1.0E-4_peaks
Caused by: ERROR lateinit property sampleItem has not been initialized
kotlin.UninitializedPropertyAccessException: lateinit property sampleItem has not been initialized
	at org.jetbrains.bio.browser.tracks.BigBedTrackView.doPreprocess(BigBedTrackView.kt:307)
	at org.jetbrains.bio.browser.tracks.BigBedTrackView$Companion$fromBigBed$1.preprocessImpl(BigBedTrackView.kt:363)
	at org.jetbrains.bio.browser.tracks.TrackView.preprocess(TrackView.kt:178)
	at org.jetbrains.bio.browser.GenomeBrowser$preprocess$asTasks$1$$special$$inlined$map$lambda$1.call(GenomeBrowser.kt:284)
	at org.jetbrains.bio.browser.GenomeBrowser$preprocess$asTasks$1$$special$$inlined$map$lambda$1.call(GenomeBrowser.kt:28)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by dievsky** [comment]
The error was caused by incorrect processing of an empty file. Fixed.
