### ISSUE TITLE
Lateinit problem during screenshot within JBR

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/jbr#22]
```
[Mar 2, 2019 23:02:48] ERROR HeadlessGenomeBrowser lateinit property sampleItem has not been initialized
Caused by: ERROR TrackViewRenderingError lateinit property sampleItem has not been initialized
org.jetbrains.bio.browser.tracks.TrackViewRenderingError: lateinit property sampleItem has not been initialized
	at org.jetbrains.bio.browser.tracks.TrackView.initConfig(TrackView.kt:208)
	at org.jetbrains.bio.browser.tracks.TrackViewRenderer.renderSingleLocationModel(TrackViewRenderer.kt:64)
	at org.jetbrains.bio.browser.tracks.TrackViewRenderer.renderTrack(TrackViewRenderer.kt:49)
	at org.jetbrains.bio.browser.web.HeadlessGenomeBrowser$Companion.renderTrackAndShowErrors$jbr_base_main(HeadlessGenomeBrowser.kt:192)
	at org.jetbrains.bio.browser.web.HeadlessGenomeBrowser$Companion$renderTracks$$inlined$time$lambda$1.call(HeadlessGenomeBrowser.kt:146)
	at org.jetbrains.bio.browser.web.HeadlessGenomeBrowser$Companion$renderTracks$$inlined$time$lambda$1.call(HeadlessGenomeBrowser.kt:62)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by dievsky** [comment]
Most likely related to #20 , and thus already fixed.
