### ISSUE TITLE
CME in JBR while loading bunch of SPAN models

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/jbr#60]
Models are uploaded from `from /mnt/stripe/shpynov/GSE65360/fit_100xstart_100iteration_1dl`
```
[Apr 11, 2019 12:38:47] ERROR TrackViewRenderComponent null
Caused by: ERROR
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at org.jetbrains.bio.browser.span.SpanModelTrackView.initConfig(SpanModelTrackView.kt:126)
	at org.jetbrains.bio.browser.tracks.TrackViewRenderer.renderSingleLocationModel(TrackViewRenderer.kt:99)
	at org.jetbrains.bio.browser.tracks.TrackViewRenderer.renderTrack(TrackViewRenderer.kt:54)
	at org.jetbrains.bio.browser.desktop.TrackViewRenderComponent$restart$1.call(TrackViewRenderComponent.kt:85)
	at org.jetbrains.bio.browser.desktop.TrackViewRenderComponent$restart$1.call(TrackViewRenderComponent.kt:29)
	at org.jetbrains.bio.util.CancellableTask$execute$1.call(CancellableTask.kt:47)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

[Apr 11, 2019 12:38:47] ERROR TrackViewRenderComponent null
Caused by: ERROR
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at org.jetbrains.bio.browser.span.SpanModelTrackView.initConfig(SpanModelTrackView.kt:126)
	at org.jetbrains.bio.browser.tracks.TrackViewRenderer.renderSingleLocationModel(TrackViewRenderer.kt:99)
	at org.jetbrains.bio.browser.tracks.TrackViewRenderer.renderTrack(TrackViewRenderer.kt:54)
	at org.jetbrains.bio.browser.desktop.TrackViewRenderComponent$restart$1.call(TrackViewRenderComponent.kt:85)
	at org.jetbrains.bio.browser.desktop.TrackViewRenderComponent$restart$1.call(TrackViewRenderComponent.kt:29)
	at org.jetbrains.bio.util.CancellableTask$execute$1.call(CancellableTask.kt:47)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by olegs** [comment]
It looks like happened on Java11.

**Comment by PetrTsurinov** [comment]
Changed peaksChrMap from MutableMap to ConcurrentHashMap.
