### ISSUE TITLE
JBR fails to load BED3 file with empty last line

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/jbr#62]
File example: 
```
chr1	12468388	12468792
chr1	202197197	202199808
chr1	40627668	40628104
chr12	125366205	125366566
chr12	6548920	6549223
chr14	63770148	63770608
chr17	49714508	49716767
chr17	58232688	58233273
chr17	83070383	83070655
chr2	112958780	112959234
chr2	166092932	166093270
chr2	202619825	202620141
chr21	15224342	15224879
chr21	34836036	34836580
chr3	122060365	122060422
chr3	43473773	43473825
chr3	88108742	88109191
chr5	77865025	77865360
chr8	34471359	34471684
chr9	113187914	113188673

```

Exception
```
Caused by: ERROR invalid BED: ''
java.lang.IllegalArgumentException: invalid BED: ''
	at org.jetbrains.bio.io.BedParser.parse(Bed.kt:317)
	at org.jetbrains.bio.io.BedParser.access$parse(Bed.kt:281)
	at org.jetbrains.bio.io.BedParser$iterator$1.next(Bed.kt:294)
	at org.jetbrains.bio.io.BedParser$iterator$1.next(Bed.kt:289)
	at kotlin.sequences.TransformingIndexedSequence$iterator$1.next(Sequences.kt:196)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
	at org.jetbrains.bio.browser.tracks.BedLocationTrackView$preprocessImpl$1.invoke(BedLocationTrackView.kt:359)
	at org.jetbrains.bio.browser.tracks.BedLocationTrackView$preprocessImpl$1.invoke(BedLocationTrackView.kt:35)
	at org.jetbrains.bio.browser.tracks.BedLocationTrackView$Companion$processBed$1.invoke(BedLocationTrackView.kt:264)
	at org.jetbrains.bio.browser.tracks.BedLocationTrackView$Companion$processBed$1.invoke(BedLocationTrackView.kt:206)
	at org.jetbrains.bio.io.BedFormat.parse(Bed.kt:84)
	at org.jetbrains.bio.io.BedFormat.parse(Bed.kt:65)
	at org.jetbrains.bio.browser.tracks.BedLocationTrackView$Companion.processBed(BedLocationTrackView.kt:252)
	at org.jetbrains.bio.browser.tracks.BedLocationTrackView.preprocessImpl(BedLocationTrackView.kt:96)
	at org.jetbrains.bio.browser.tracks.TrackView.preprocess(TrackView.kt:175)
	at org.jetbrains.bio.browser.GenomeBrowser$preprocess$asTasks$1$$special$$inlined$map$lambda$1.call(GenomeBrowser.kt:288)
	at org.jetbrains.bio.browser.GenomeBrowser$preprocess$asTasks$1$$special$$inlined$map$lambda$1.call(GenomeBrowser.kt:29)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by olegs** [comment]
Happened with last released version.

**Comment by dievsky** [comment]
Reassigning to myself, since I did the last BED parsing upgrade.

A completely failsafe (or rather, as failsafe as humanly possible) BED parsing approach would be to ignore any lines that can't be parsed as at least `BED3+`.

**Comment by dievsky** [comment]
We have some very curious choices when parsing a BED. The line `chr1 foo bar` will just log an error and return a [0, 0] range on `chr1`, while `chr1 foo` will throw an uncaught exception which, even if caught upstream, completely prevents further parsing (since that context is exited from).

A more consistent choice would be to either throw on any unparseable line (very, VERY bad, since so many BEDs have comments, headers and empty lines), or omit it (and log an error).

**Comment by dievsky** [comment]
At the long last, the empty-line BED file can be loaded into JBR with no issues.
