### ISSUE TITLE
MACS2 broad peaks: ERROR Value out of range. Value:"42682" Radix:10

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/jbr#67]
Score in *.broadPeak files could be more than Short.MAX, e.g. `42682` which doesn't match BED specs. Autoformat doesn't handle it because first lines are ok.

```
# /mnt/stripe/rcherniatchik/GSE63523_check/me/GSM1551533_broad_0.1_PE_peaks.broadPeak
chr2	98666549	98667327	GSM1551533_broad_0.1_PE_peak_5582	42682	.	10.85039	4275.01855	4268.24658
```

this causes:

```
[Nov 13, 2018 13:52:29 ERROR TrackView] Failed to preprocess track GSM1551533_broad_0.1_PE_peaks.broadPeak
Caused by: ERROR Value out of range. Value:"42682" Radix:10
java.lang.NumberFormatException: Value out of range. Value:"42682" Radix:10
	at java.lang.Short.parseShort(Short.java:120)
	at java.lang.Short.parseShort(Short.java:144)
	at org.jetbrains.bio.big.BedEntry.unpack(Bed.kt:83)
	at org.jetbrains.bio.big.BedEntry.unpack$default(Bed.kt:64)
	at org.jetbrains.bio.browser.tracks.impl.BedLocationTrackView$Companion$processBed$1$res$1.invoke(BedLocationTrackView.kt:293)
	at org.jetbrains.bio.browser.tracks.impl.BedLocationTrackView$Companion$processBed$1$res$1.invoke(BedLocationTrackView.kt:241)
	at kotlin.sequences.TransformingIndexedSequence$iterator$1.next(Sequences.kt:173)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:109)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:133)
	at org.jetbrains.bio.browser.tracks.impl.BedLocationTrackView$preprocessImpl$1.invoke(BedLocationTrackView.kt:345)
	at org.jetbrains.bio.browser.tracks.impl.BedLocationTrackView$preprocessImpl$1.invoke(BedLocationTrackView.kt:41)
	at org.jetbrains.bio.browser.tracks.impl.BedLocationTrackView$Companion$processBed$1.invoke(BedLocationTrackView.kt:299)
	at org.jetbrains.bio.browser.tracks.impl.BedLocationTrackView$Companion$processBed$1.invoke(BedLocationTrackView.kt:241)
	at org.jetbrains.bio.io.BedFormat.parse(Bed.kt:82)
	at org.jetbrains.bio.io.BedFormat.parse(Bed.kt:64)
	at org.jetbrains.bio.browser.tracks.impl.BedLocationTrackView$Companion.processBed(BedLocationTrackView.kt:287)
	at org.jetbrains.bio.browser.tracks.impl.BedLocationTrackView.preprocessImpl(BedLocationTrackView.kt:100)
	at org.jetbrains.bio.browser.tracks.TrackView.preprocess(TrackView.kt:173)
	at org.jetbrains.bio.browser.GenomeBrowser$preprocess$asTasks$1$$special$$inlined$map$lambda$1.call(GenomeBrowser.kt:286)
	at org.jetbrains.bio.browser.GenomeBrowser$preprocess$asTasks$1$$special$$inlined$map$lambda$1.call(GenomeBrowser.kt:28)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by iromeo** [comment]
Same issue as in #65
