### ISSUE TITLE
NPE in ENCODE search

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/jbr#86]
Pretending to be an incorrect syntax.

```
Caused by: ERROR
java.lang.NullPointerException
	at org.jetbrains.bio.browser.ui.SearchEncodeUtil.queryFile$jbr_encode_search(SearchEncodeUtil.kt:81)
	at org.jetbrains.bio.browser.ui.SearchEncodeUtil$queryFile$1.invokeSuspend(SearchEncodeUtil.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:215)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:215)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)

[Dec 19, 2019 15:51:56] ERROR SearchEncodeUtil Unexpected response syntax
Caused by: ERROR
java.lang.NullPointerException
	at org.jetbrains.bio.browser.ui.SearchEncodeUtil.queryFile$jbr_encode_search(SearchEncodeUtil.kt:81)
	at org.jetbrains.bio.browser.ui.SearchEncodeUtil$queryFile$1.invokeSuspend(SearchEncodeUtil.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:215)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:215)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by dievsky** [comment]
Since this NPE occurs when parsing the response JSON, it _is_ a case of unexpected syntax. :)) Could you specify which file / which experiment were you viewing?

**Comment by olegs** [comment]
<img width="478" alt="Screenshot 2019-12-19 at 16 46 28" src="https://user-images.githubusercontent.com/75644/71178380-24188880-227f-11ea-93d6-3ba6f336783e.png">

**Comment by dievsky** [comment]
Thanks! This turned to be an SRR file which can't be downloaded, probably due to some privacy and/or data protection issues. We need to make this more obvious to the user, naturally.

**Comment by dievsky** [comment]
Should be fixed now.

**Comment by olegs** [comment]
Works as a charm, closing the issue.
