### ISSUE TITLE
SearchEncodeUtil Exception during ENCODE search

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/jbr#92]
Open hg38 assembly. 
Launch ENCODE search for h3k4me1.
Expand node `ChIP-seq against H3K4me1 using SK-N-MC cell ...`
Get the following exception in console.

```
[Jan 14, 2020 17:35:46] ERROR SearchEncodeUtil Exception
Caused by: ERROR SSLPeerUnverifiedException peer not authenticated
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at java.base/sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:526)
	at org.apache.http.nio.conn.ssl.SSLIOSessionStrategy.verifySession(SSLIOSessionStrategy.java:205)
	at org.apache.http.nio.conn.ssl.SSLIOSessionStrategy$1.verify(SSLIOSessionStrategy.java:188)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:354)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:503)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by dievsky** [comment]
Probably the same as #85. ENCODE seems to upgrade the connection to HTTPS at some point.

The problem is that I can't reproduce this; this error never happened to me. My best guess is that the cause of the problem lies within the difference between our respective Java runtimes and their SSL configurations.

Could you launch JBR with `-Djavax.net.debug=ssl:handshake` JVM option and verify that the terminal output contains
```
adding as trusted cert:
  Subject: CN=GlobalSign Root CA, OU=Root CA, O=GlobalSign nv-sa, C=BE
```
?

(I'd ask to just attach the whole output here but I'm not sure that it wouldn't leak confidential data.)

**Comment by dievsky** [comment]
Internet suggests that not all JDKs have the same certificate store, and that the discrepancies are explained by whether and when the certificate owner signed a specific contract with Oracle.

For confirmation, I'd like to ask you to locate the `cacerts` file bundled with your JDK, e.g.:
```
locate cacerts | grep "oracle-11-java"
```
and then paste here the output of
```
keytool -list -v -keystore </path/to/cacerts> | grep GlobalSign
```
This doesn't contain any sensitive data. The default keystore password is `changeit`.

**Comment by olegs** [comment]
Cannot reproduce the issue anymore. However here is the desired information:
```
unit-1199:~ oleg$ keytool -list -v -keystore /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home/lib/security/cacerts | grep GlobalSign
Enter keystore password:  changeit
Owner: CN=GlobalSign, O=GlobalSign, OU=GlobalSign Root CA - R2
Issuer: CN=GlobalSign, O=GlobalSign, OU=GlobalSign Root CA - R2
Owner: CN=GlobalSign, O=GlobalSign, OU=GlobalSign ECC Root CA - R4
Issuer: CN=GlobalSign, O=GlobalSign, OU=GlobalSign ECC Root CA - R4
Owner: CN=GlobalSign Root CA, OU=Root CA, O=GlobalSign nv-sa, C=BE
Issuer: CN=GlobalSign Root CA, OU=Root CA, O=GlobalSign nv-sa, C=BE
Owner: CN=GlobalSign, O=GlobalSign, OU=GlobalSign Root CA - R3
Issuer: CN=GlobalSign, O=GlobalSign, OU=GlobalSign Root CA - R3
Owner: CN=GlobalSign, O=GlobalSign, OU=GlobalSign ECC Root CA - R5
Issuer: CN=GlobalSign, O=GlobalSign, OU=GlobalSign ECC Root CA - R5
```

**Comment by dievsky** [comment]
Thanks! The required certificates are in place, so everything should work.

This also might be an intermittent problem with the ENCODE server being too busy to send certificates. ENCODE is much, much less responsive in the (European) afternoon than in the (European) morning.

Should we close the issue as can't-reproduce?

**Comment by olegs** [comment]
Yep, closing as can't reproduce, will reopen once face the problem again.
